version: "3"
services:
  broker-rabbitmq:
    image: "rabbitmq:3.7.14-management"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbit_user
      - RABBITMQ_DEFAULT_PASS=rabbit_password
  db-postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=db_user
      - POSTGRES_PASSWORD=db_password
      - POSTGRES_DB=subway_usage_dev
    ports:
      - "5432:5432"

  # migration:
  #   build: .
  #   environment:
  #     - APP_ENV=${APP_ENV}
  #   command: flask db upgrade
  #   depends_on:
  #     - db-postgres
  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
    command: ["/subway-usage/docker-entrypoint.sh"]
  api-worker:
    build: .
    command: celery worker --workdir=. -A tasks.celery --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
  api-beat:
    build: .
    command: celery beat -A tasks.celery --loglevel=info
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - broker-rabbitmq
      - db-postgres
      # - migration
# version: "3.6"

# services:
#   api:
#     build: .
#     depends_on:
#       - db
#     environment:
#       STAGE: test
#       SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://test:test@db/test
#     networks:
#       - default
#     ports:
#       - 5000:5000
#     volumes:
#       - ./app:/usr/src/app/app
#       - ./migrations:/usr/src/app/migrations
#     restart: always

#   db:
#     environment:
#       POSTGRES_USER: test
#       POSTGRES_PASSWORD: test
#       POSTGRES_DB: test
#     image: postgres:latest
#     networks:
#       - default
#     ports:
#       - 5405:5432
#     restart: always
#     volumes:
#       - ./postgres-data:/var/lib/postgresql/data
